<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>assets\senji.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>SenjiDownloader</AssemblyName>
    <RootNamespace>SenjiDownloader</RootNamespace>
    <Version>1.0.1</Version>
    <Authors>SenjiDownloader</Authors>
    <Product>SenjiDownloader</Product>
    <Description>Descargas y conversiones de medios en paralelo.</Description>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
    <DebugType>embedded</DebugType>
    <SatelliteResourceLanguages>es;en</SatelliteResourceLanguages>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="assets\senji.ico" />
    <EmbeddedResource Include="assets\tools.zip" LogicalName="SenjiDownloader.tools.zip" Condition="Exists('assets\tools.zip')" />
  </ItemGroup>
</Project>
